version: '3.8'

services: 
    nginx:
        build: ./nginx
        depends_on: 
            - node
        ports: 
            - 80:80

    node:
        build: ./node
        depends_on: 
            - mysql
            - redis
        expose: 
            - "3000"

    mysql:
        build: ./mysql
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        build: ./redis
        ports: 
            - 6379:6379
