version: '3'

services: 
    nginx:
        build: ./nginx
        depends_on: 
            - node
        ports: 
            - 80:80

    node:
        build: ./node
        ports: 
            - 3000:3000

    mysql:
        build: ./mysql
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        build: ./phpmyadmin
        restart: always
        ports: 
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

    redis:
        build: ./redis
        ports: 
            - 6379:6379
