version: '3.8'

services: 
    nginx:
        build: ./nginx
        depends_on: 
            - node
        ports: 
            - 80:80

    node:
        build: ./node
        depends_on: 
            - mysql
            - redis
        volumes: 
            - ./node/project:/project
        expose: 
            - "3000"

    mysql:
        image: mysql:5.7
        restart: always
        ports: 
            - 3306:3306
        volumes: 
            - ./mysql/data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:latest
        ports: 
            - 6379:6379

    phpmyadmin:
        image: phpmyadmin:latest
        depends_on: 
            - mysql
        restart: always
        ports:
        - 8080:80
        environment:
        - PMA_ARBITRARY=1
